select Count(OrderNumber) as ordenes_por_subcategoria,product_subcategories.SubcategoryName
from sales_2020
join products on sales_2020.ProductKey=products.ProductKey
join product_subcategories on products.ProductSubcategoryKey=product_subcategories.ProductSubcategoryKey
group by product_subcategories.SubcategoryName
order by ordenes_por_subcategoria desc